# Generated by Django 4.2.13 on 2024-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalBlogersAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Открыт'), (2, 'В клубе'), (3, 'Связалась, жду ответ'), (4, 'Не отвечает'), (5, 'Зайдет позже')], default=1, verbose_name='Статус')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше имя и фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город проживания')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы, должность')),
                ('speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('blog_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на социальные сети / блог')),
                ('expectations', models.TextField(blank=True, null=True, verbose_name='Ваши ожидания от участия в Национальной Ассоциации блогеров в сфере здравоохранения')),
                ('policy_agreement', models.BooleanField(default=False, verbose_name='Согласен с политикой обработки персональных данных')),
            ],
            options={
                'verbose_name': 'запись в анкете Национальная ассоциация блогеров в сфере здравоохранения',
                'verbose_name_plural': 'Анкета Национальная ассоциация блогеров в сфере здравоохранения',
            },
        ),
    ]
