# Generated by Django 4.2.13 on 2025-03-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0002_nationalblogersassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medblogerspreentry',
            name='is_in_mailing_list',
            field=models.BooleanField(default=False, verbose_name='Есть ли в рассылке'),
        ),
    ]
