# Generated by Django 4.2.13 on 2025-06-15 14:39

import business_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0002_nationalblogersassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressMedbloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_type', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('bot', 'Рассылка в боте'), ('email', 'Рассылка на почте')], max_length=255, null=True, verbose_name='Вы увидели эту анкету у меня в')),
                ('have_bought_products', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вы покупали какие-то мои продукты?')),
                ('speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация (гинеколог, невролог и т.д.)')),
                ('average_income', models.CharField(blank=True, choices=[('0-50', 'до 50тыс'), ('50-100', '50 - 100тыс'), ('100-150', '100 - 150тыс'), ('150-200', '150 - 200тыс'), ('200-300', '200 - 300тыс'), ('300-500', '300 - 500тыс'), ('500-1кк', '500тыс - 1млн'), ('1кк+', '1млн+')], max_length=255, null=True, verbose_name='Ваш средний доход в месяц, в рублях, суммарный со всех источников')),
                ('medblog', models.CharField(blank=True, choices=[('yes_money', 'Веду, получаю с него стабильный доход'), ('yes_no_money', 'Веду, но не очень результативно / не зарабатываю с него'), ('no', 'Не веду, только планирую завести')], max_length=255, null=True, verbose_name='Медблог:')),
                ('medblog_reason', models.TextField(blank=True, null=True, verbose_name='Зачем вы ведёте / хотите вести медблог?')),
                ('medblog_complexity', models.TextField(blank=True, null=True, verbose_name='Какие сложности есть сейчас с блогом? Что останавливает от того, чтобы достичь целей выше?')),
                ('medblog_helped', models.TextField(blank=True, null=True, verbose_name='Что уже пробовали делать, чтобы решить проблему? Что помогло, а что - не очень?')),
                ('how_long_following', models.TextField(blank=True, null=True, verbose_name='Как давно вы на меня подписаны и откуда узнали?')),
                ('top_questions', models.TextField(blank=True, null=True, verbose_name='ТОП-1 или ТОП-3 вопроса по блогингу, которые вы хотите решить прямо сейчас:')),
                ('how_warmed_up', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=255, null=True, verbose_name='На сколько от 0 до 10 вы прогреты, чтобы начать у меня обучение любого формата?')),
                ('rate_of_employment', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=255, null=True, verbose_name='Оцените уровень вашей занятости от 0 до 10')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше ФИО')),
                ('age', models.CharField(blank=True, max_length=255, null=True, verbose_name='Возраст')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город проживания в настоящий момент')),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ваш инстаграм')),
                ('tg_channel_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ваш телеграм-канал')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ваш личный телеграм (не канал) в формате https://t.me/readydoc или через @')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('policy_agreement', models.BooleanField(default=False, verbose_name='Согласен с политикой обработки персональных данных')),
            ],
            options={
                'verbose_name': "запись в анкете 'Экспресс-разбор медблога'",
                'verbose_name_plural': "Анкета 'Экспресс-разбор медблога'",
            },
            bases=(models.Model, business_forms.models.BaseModelForm),
        ),
    ]
