# Generated by Django 4.2.13 on 2025-06-17 17:11

import business_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0003_expressmedbloger'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroMedbloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше ФИО')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город проживания в настоящий момент')),
                ('speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация (гинеколог, невролог и т.д.)')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ваш личный телеграм (не канал) в формате https://t.me/readydoc или через @')),
                ('level_of_use_neuro', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=255, null=True, verbose_name='Оцените уровень вашего пользования нейросетями для создания контента')),
                ('your_questions', models.TextField(blank=True, null=True, verbose_name='Ваши вопросы')),
                ('policy_agreement', models.BooleanField(default=False, verbose_name='Согласен с политикой обработки персональных данных')),
            ],
            options={
                'verbose_name': "запись в анкете 'Нейросети для медблога'",
                'verbose_name_plural': "Анкета 'Нейросети для медблога'",
            },
            bases=(models.Model, business_forms.models.BaseModelForm),
        ),
    ]
