# Generated by Django 4.2.13 on 2025-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0004_neuromedbloger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMMSpecialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255, verbose_name='Ваша специализация')),
                ('social_networks', models.CharField(max_length=255, verbose_name='В каких соцсетях вы ведёте блог?')),
                ('your_experience', models.CharField(db_column='your_experience', max_length=500, verbose_name='Обращались ли вы за помощью к digital специалистам? (если нужной профессии нет в списке, напишите в последней строке)')),
                ('last_collaboration_period', models.CharField(choices=[('3_month', 'До 3 месяцев'), ('3_6_month', '3-6 месяцев'), ('1_year', 'До года'), ('More_1_year', 'Более года')], db_column='last_collaboration_period', max_length=255, verbose_name='Сколько продлилось ваше сотрудничество?')),
                ('satisfied_of_results', models.CharField(choices=[('all_good', 'Всё было отлично, сотрудничество помогло решить задачи'), ('50_50', 'В целом неплохо, но есть нюансы'), ('bad_exp', 'Нет, ожидания не оправдались')], db_column='satisfied_of_results', max_length=255, verbose_name='Довольны ли результатами?')),
                ('positive_specialist_contact', models.CharField(db_column='positive_specialist_contact', max_length=500, verbose_name='Оставьте контакт на своего digital специалиста, если готовы его рекомендовать')),
                ('negative_specialist_contact', models.CharField(db_column='neg_specialist_contact', max_length=500, verbose_name='А в этом окне оставьте контакт digital специалиста, с которым НЕ рекомендуете сотрудничать')),
                ('user_contact', models.CharField(db_column='user_contact', max_length=255, verbose_name='Если вы готовы пообщаться с нами подробнее на тему СММ и подбора проверенных подрядчиков, оставьте свой телеграм через @ или ссылкой')),
            ],
            options={
                'verbose_name': "запись в анкете 'рекомендации SMM специалиста'",
                'verbose_name_plural': "Анкета 'рекомендации SMM специалиста'",
            },
        ),
    ]
