# Generated by Django 4.2.13 on 2025-08-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0005_smmspecialists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressmedbloger',
            name='marketing_type',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('bot', 'Рассылка в боте'), ('email', 'Рассылка на почте'), ('meducation', 'Блог Meducation')], max_length=255, null=True, verbose_name='Я увидел(а) эту анкету в:'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='last_collaboration_period',
            field=models.CharField(blank=True, choices=[('3_month', 'До 3 месяцев'), ('3_6_month', '3-6 месяцев'), ('1_year', 'До года'), ('More_1_year', 'Более года')], db_column='last_collaboration_period', max_length=255, null=True, verbose_name='Сколько продлилось ваше сотрудничество?'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='negative_specialist_contact',
            field=models.CharField(blank=True, db_column='neg_specialist_contact', max_length=500, null=True, verbose_name='А в этом окне оставьте контакт digital специалиста, с которым НЕ рекомендуете сотрудничать'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='positive_specialist_contact',
            field=models.CharField(blank=True, db_column='positive_specialist_contact', max_length=500, null=True, verbose_name='Оставьте контакт на своего digital специалиста, если готовы его рекомендовать'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='satisfied_of_results',
            field=models.CharField(blank=True, choices=[('all_good', 'Всё было отлично, сотрудничество помогло решить задачи'), ('50_50', 'В целом неплохо, но есть нюансы'), ('bad_exp', 'Нет, ожидания не оправдались')], db_column='satisfied_of_results', max_length=255, null=True, verbose_name='Довольны ли результатами?'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='social_networks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В каких соцсетях вы ведёте блог?'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваша специализация'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='user_contact',
            field=models.CharField(blank=True, db_column='user_contact', max_length=255, null=True, verbose_name='Если вы готовы пообщаться с нами подробнее на тему СММ и подбора проверенных подрядчиков, оставьте свой телеграм через @ или ссылкой'),
        ),
        migrations.AlterField(
            model_name='smmspecialists',
            name='your_experience',
            field=models.CharField(blank=True, db_column='your_experience', max_length=500, null=True, verbose_name='Обращались ли вы за помощью к digital специалистам? (если нужной профессии нет в списке, напишите в последней строке)'),
        ),
    ]
