# Generated by Django 4.2.13 on 2026-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0006_alter_expressmedbloger_marketing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressmedbloger',
            name='marketing_type',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('bot', 'Рассылка в боте'), ('email', 'Рассылка на почте'), ('meducation', 'Блог Meducation'), ('nastav_readydoc', 'Сайт наставничества Владимира Нечепорука'), ('nastav_speecadoc', 'Сайт наставничества Екатерины Спицыной')], max_length=255, null=True, verbose_name='Я увидел(а) эту анкету в:'),
        ),
    ]
