# Generated by Django 4.2.13 on 2026-02-23 11:17

import business_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0008_speecadoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedSMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Отметка времени')),
                ('marketing_type', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('bot', 'Рассылка в боте'), ('email', 'Рассылка на почте')], max_length=255, null=True, verbose_name='Вы увидели эту анкету у меня в:')),
                ('age_range', models.CharField(blank=True, choices=[('18-', 'до 18'), ('18-24', '18-24'), ('25-30', '25-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41-45', '41-45'), ('46-51', '46-51'), ('52+', '52+')], max_length=255, null=True, verbose_name='Ваш возраст')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Чем вы сейчас занимаетесь? (род деятельности)')),
                ('average_income', models.CharField(blank=True, choices=[('0-50', 'до 50 тыс'), ('50-100', '50 - 100 тыс'), ('100-150', '100 - 150 тыс'), ('150-200', '150 - 200 тыс'), ('200-300', '200 - 300 тыс'), ('300-500', '300 - 500 тыс'), ('500+', 'свыше 500 тыс')], max_length=255, null=True, verbose_name='Ваш средний доход в месяц, в рублях (суммарный со всех источников)')),
                ('reason_for_career_change', models.TextField(blank=True, null=True, verbose_name='Почему задумываетесь о смене профессии?')),
                ('disappointment_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=255, null=True, verbose_name='Оцените уровень разочарования в профессии врача от 0 до 10')),
                ('tried_blogging', models.CharField(blank=True, choices=[('personal', 'Личный'), ('expert', 'Экспертный'), ('other_person', 'Чужой'), ('never', 'Никогда')], max_length=255, null=True, verbose_name='Вы пробовали вести блог? (в любой соцсети)')),
                ('smm_education', models.CharField(blank=True, choices=[('paid', 'Платные курсы'), ('free', 'Бесплатные материалы'), ('none', 'Не обучался')], max_length=255, null=True, verbose_name='Вы уже обучались где-то SMM / маркетингу / блогингу?')),
                ('skills', models.CharField(blank=True, max_length=500, null=True, verbose_name='Что умеете делать?')),
                ('smm_work_vision', models.TextField(blank=True, null=True, verbose_name='Как вы представляете работу SMM-специалиста?')),
                ('desired_income', models.CharField(blank=True, choices=[('20-30', '20 - 30 тыс'), ('30-60', '30 - 60 тыс'), ('60-100', '60 - 100 тыс'), ('100+', '100 тыс+')], max_length=255, null=True, verbose_name='Какой доход в SMM через 6 месяцев был бы для вас успехом (в месяц в рублях)')),
                ('top_fears', models.TextField(blank=True, null=True, verbose_name='Что для вас самое страшное в работе SMM на текущий момент? ТОП-3 страха')),
                ('investment_readiness', models.CharField(blank=True, choices=[('20-30', '20 - 30 тыс'), ('30-50', '30 - 50 тыс'), ('50-100', '50 - 100 тыс'), ('100+', '100+ тыс')], max_length=255, null=True, verbose_name='Сколько готовы вложить в освоение новой профессии SMM?')),
                ('five_year_plan', models.TextField(blank=True, null=True, verbose_name='Кем и где вы хотите работать через 5 лет и сколько зарабатывать?')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваши Имя и Фамилия')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город проживания в настоящий момент')),
                ('instagram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ваш инстаграм')),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на ваш личный телеграм (не канал) в формате https://t.me/readydoc или через @')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона через +7')),
                ('policy_agreement', models.BooleanField(default=False, verbose_name='Даю согласие на обработку персональных данных')),
            ],
            options={
                'verbose_name': "запись в анкете 'Опрос для будущих мед. SMM-специалистов'",
                'verbose_name_plural': "Анкета 'Опрос для будущих мед. SMM-специалистов'",
            },
            bases=(models.Model, business_forms.models.BaseModelForm),
        ),
        migrations.AlterField(
            model_name='expressmedbloger',
            name='marketing_type',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('bot', 'Рассылка в боте'), ('email', 'Рассылка на почте'), ('meducation', 'Блог Meducation')], max_length=255, null=True, verbose_name='Я увидел(а) эту анкету в:'),
        ),
    ]
